import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/layout/Navbar";
import Landing from "../components/home/Landing";
import ZoomSection from "../components/home/ZoomSection";
import ScrollAnimation from "../components/home/ScrollAnimation";
import ProjectCard from "../components/home/ProjectCard";
import { projects } from "../data/projects";

const Home: NextPage = () => {
  return (
    <div className={styles.main}>
      <Head>
        <title>Vansh Sood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="min-h-screen bg-black">
        {/* <ScrollAnimation> */}
        <div className="flex flex-col justify-center items-center text-center h-full">
          <h1 className="text-6xl font-bold color-4">
            Hi! I'm Vansh, a Creative Developer
          </h1>
          <p className="color-4">
            Trying to bring a change by empowering international students to
            leverage Freelancing over conventional part-time
          </p>
        </div>
        {/* </ScrollAnimation> */}
      </div>
      <div className="h-[500px]"></div>
      <div className="bg-white">
        <ProjectCard data={projects} />
      </div>
    </div>
  );
};

export default Home;
